export const DUNGEONS = {
    1: {
        id: 'DUNGEON_T1',
        name: 'Goblin Cave',
        tier: 1,
        reqItem: 'T1_DUNGEON_MAP',
        waves: 5,
        bossId: 'BOSS_GOBLIN_KING',
        trashMobs: ['RABBIT', 'GOBLIN_SCOUT', 'ROCK_ELEMENTAL_T1', 'GIANT_SPIDER_T1'],
        reqLevel: 1,
        rewards: {
            xp: 120,
            silver: 200,
            resource: { id: 'T1_ORE', chance: 0.50, min: 5, max: 10 },
            crest: { id: 'T1_CREST', chance: 0.25 }
        },
        entrySilver: 200,
    },
    2: {
        id: 'DUNGEON_T2',
        name: 'Wolf Den',
        tier: 2,
        reqItem: 'T2_DUNGEON_MAP',
        waves: 5,
        bossId: 'BOSS_WOLF_ALPHA',
        trashMobs: ['WOLF', 'DIRE_RAT', 'FOREST_SPIRIT', 'BANDIT_SCOUT'],
        reqLevel: 10,
        rewards: {
            xp: 180,
            silver: 500,
            resource: { id: 'T2_WOOD', chance: 0.50, min: 5, max: 10 },
            crest: { id: 'T2_CREST', chance: 0.25 }
        },
        entrySilver: 500,
    },
    3: {
        id: 'DUNGEON_T3',
        name: 'Bear Cave',
        tier: 3,
        reqItem: 'T3_DUNGEON_MAP',
        waves: 5,
        bossId: 'BOSS_BEAR_ANCIENT',
        trashMobs: ['BEAR', 'MOUNTAIN_GOBLIN', 'SKELETON', 'SKELETON_WARRIOR'],
        reqLevel: 20,
        rewards: {
            xp: 240,
            silver: 1000,
            resource: { id: 'T3_HIDE', chance: 0.50, min: 5, max: 10 },
            crest: { id: 'T3_CREST', chance: 0.25 }
        },
        entrySilver: 1000,
    },
    4: {
        id: 'DUNGEON_T4',
        name: 'Undead Crypt',
        tier: 4,
        reqItem: 'T4_DUNGEON_MAP',
        waves: 5,
        bossId: 'BOSS_SKELETON_KING',
        trashMobs: ['DIRE_WOLF', 'GHOST_KNIGHT', 'UNDEAD_SOLDIER', 'CRYPT_WARDEN'],
        reqLevel: 30,
        rewards: {
            xp: 315,
            silver: 2500,
            resource: { id: 'T4_BAR', chance: 0.50, min: 3, max: 8 },
            crest: { id: 'T4_CREST', chance: 0.25 }
        },
        entrySilver: 2500,
    },
    5: {
        id: 'DUNGEON_T5',
        name: 'Ogre Fortress',
        tier: 5,
        reqItem: 'T5_DUNGEON_MAP',
        waves: 5,
        bossId: 'BOSS_OGRE_CHIEFTAIN',
        trashMobs: ['OGRE', 'WAR_OGRE', 'LICH', 'LICH_LORD'],
        reqLevel: 40,
        rewards: {
            xp: 396,
            silver: 5000,
            resource: { id: 'T5_HIDE', chance: 0.50, min: 3, max: 8 },
            crest: { id: 'T5_CREST', chance: 0.25 }
        },
        entrySilver: 5000,
    },
    6: {
        id: 'DUNGEON_T6',
        name: 'Troll Mountain',
        tier: 6,
        reqItem: 'T6_DUNGEON_MAP',
        waves: 5,
        bossId: 'BOSS_TROLL_ELDER',
        trashMobs: ['TROLL', 'ARMORED_TROLL', 'FIRE_ELEMENTAL', 'INFERNAL_ELEMENTAL'],
        reqLevel: 50,
        rewards: {
            xp: 480,
            silver: 10000,
            resource: { id: 'T6_ORE', chance: 0.50, min: 3, max: 8 },
            crest: { id: 'T6_CREST', chance: 0.25 }
        },
        entrySilver: 10000,
    },
    7: {
        id: 'DUNGEON_T7',
        name: 'Dragon Nest',
        tier: 7,
        reqItem: 'T7_DUNGEON_MAP',
        waves: 5,
        bossId: 'BOSS_DRAGON_MOTHER',
        trashMobs: ['DRAGON_WHELP', 'FIRE_DRAKE', 'DARK_KNIGHT', 'DEATH_KNIGHT'],
        reqLevel: 60,
        rewards: {
            xp: 565,
            silver: 20000,
            resource: { id: 'T7_HIDE', chance: 0.50, min: 2, max: 6 },
            crest: { id: 'T7_CREST', chance: 0.25 }
        },
        entrySilver: 20000,
    },
    8: {
        id: 'DUNGEON_T8',
        name: 'Ancient Ruins',
        tier: 8,
        reqItem: 'T8_DUNGEON_MAP',
        waves: 5,
        bossId: 'BOSS_GOLEM_PRIMORDIAL',
        trashMobs: ['ANCIENT_GOLEM', 'OBSIDIAN_GOLEM', 'DEMON', 'DEMON_WARRIOR'],
        reqLevel: 70,
        rewards: {
            xp: 652,
            silver: 40000,
            resource: { id: 'T8_ORE', chance: 0.50, min: 2, max: 6 },
            crest: { id: 'T8_CREST', chance: 0.25 }
        },
        entrySilver: 40000,
    },
    9: {
        id: 'DUNGEON_T9',
        name: 'Demon Realm',
        tier: 9,
        reqItem: 'T9_DUNGEON_MAP',
        waves: 5,
        bossId: 'BOSS_DEMON_PRINCE',
        trashMobs: ['ELDER_DRAGON', 'VOID_DRAGON', 'ARCHDEMON', 'ABYSSAL_FIEND'],
        reqLevel: 80,
        rewards: {
            xp: 740,
            silver: 100000,
            resource: { id: 'T9_BAR', chance: 0.50, min: 2, max: 5 },
            crest: { id: 'T9_CREST', chance: 0.25 }
        },
        entrySilver: 100000,
    },
    10: {
        id: 'DUNGEON_T10',
        name: 'Void Dimension',
        tier: 10,
        reqItem: 'T10_DUNGEON_MAP',
        waves: 5,
        bossId: 'BOSS_VOID_ENTITY',
        trashMobs: ['ANCIENT_DRAGON', 'VOID_DRAGON_LORD', 'DEMON_LORD', 'VOID_EXECUTIONER'],
        reqLevel: 90,
        rewards: {
            xp: 829,
            silver: 500000,
            resource: { id: 'T10_BAR', chance: 0.50, min: 2, max: 5 },
            crest: { id: 'T10_CREST', chance: 0.25 }
        },
        entrySilver: 500000,
    }
};
